init Kea as dhcp server
ClubCedille/pixicoreAPI pull request #14
Opened 2019-02-04 11:44 UTC by mikefaille

It's a standalone projet for now in standalone folder for now. The main project isn't modified to enable a quick win and promote ISC Kea DHCP faster (over ISC Dhcpd) for his rest api.

2019-02-04 22:01 UTC, notarock commented
Le build ne fonctionne pas. Est-ce que c'est valide quand même?

2019-02-04 22:06 UTC, jalilbengoufa commented
je sais  pourquoi le build ne fonctionne pas je l'avais fix dans ma branche mais je vais le faire directement sur celle-ci.

2019-02-04 22:28 UTC, jalilbengoufa approved these changes

2019-02-04 22:32 UTC, cguertin14 approved these changes

2019-02-04 23:13 UTC, notarock approved these changes
Est-ce que `kea/kea-single-subnet.conf.tmpl` est un fichier qu'on doit copier et modifier? Dans ce cas, c'est pertinent de le conserver. Autrement, est-ce qu'il est nécessaire?

À part de ça, tout semble propre. :+1:

2019-02-05 00:27 UTC, AXDOOMER requested changes

2019-02-05 05:32 UTC, mikefaille commented on kea/kea-single-subnet.conf.tmpl
> +
Done

2019-02-05 05:32 UTC, mikefaille commented on kea/Dockerfile
> +RUN echo "/usr/local/lib/hooks" > /etc/ld.so.conf.d/kea.conf && ldconfig -v | grep kea
Fixed

2019-02-05 05:32 UTC, mikefaille commented on kea/lauch_docker.sh
> +#!/usr/bin/env bash
Fixed

2019-02-05 22:37 UTC, mikefaille commented
> Est-ce que `kea/kea-single-subnet.conf.tmpl` est un fichier qu'on doit copier et modifier? Dans ce cas, c'est pertinent de le conserver. Autrement, est-ce qu'il est nécessaire?

C'est un template de configuration. Utilisé ici : kea_bootstrapconf.sh

2019-02-06 00:54 UTC, notarock commented
Cool, merci pour la clarification! :+1:

2019-02-06 01:09 UTC, AXDOOMER approved these changes
@mikefaille  T'as l'air d'avoir tout fix, mais SVP fait pas de push-force. Fait un autre commit pour corriger tes erreurs, c'est plus facile à review, sinon faut refouiller pour retrouver où étaient les lignes qu'on a demandé de corriger. C'est la job de celui qui va merge de squash en un commit.

2019-02-06 01:31 UTC, AXDOOMER commented
Ce sont les bonnes pratiques. Parfois on fait des trucs et on a l'impression de rendre service aux autres en leur sauvant de la job, mais on leur donne plus de trouble.

2019-02-06 03:51 UTC, mikefaille commented
@AXDOOMER Tu as noté un bon problème. Il n'y a pas de traçabilité sur les contributions intermédiaires sur Github lorsqu'on fait un squash. 

Ailleurs que sur Github, cette traçabilité est toutefois possible avec un système de patch (plusieurs patch représentant un commit) et l'obligation de contribuer seulement avec des squash (aka contribution atomique / commit atomique); ici, on peut faire  référence à la mailling liste du Kernel Linux ou à tous les logiciels dont le système de revue c'est Gerrit. Or, sur la mailling list de Linux et sur Gerrit, les squash   avec force-push durant la revue sont normaux.

L'essentiel  à priori c'est qu'on fasse la revue d'un code qui sera tel quel en production. Un squash après la revue fait perdre l'intérêt pour la revue puisque rien ne prouve que le code est intact après le squash. Aussi, si la contribution est petite, c'est facile de faire le suivit. 

Par contre...
Au final, j'y pense @AXDOOMER  et je crois que tu as raison : Il faut que ça soit agréable aka painless de faire un suivit de PR. Et, un squash + force-push facilite la revue tout en concernant un historique clean. Et, on se fit à la personne qui squash pour en faire un clean.

2019-02-06 03:54 UTC, AXDOOMER commented
Github ne fait pas de push-force quand tu fais un squash.

2019-02-06 04:02 UTC, mikefaille commented
Il fait un rebase plus squash directement sur la branche master. Alors, c'est problématique alors si le rebase n'a pas été fait sur la branche courante (ce dont j'avais suppose pour le force push). Ça veut dire que ce qui est en revue n'est pas garantis que ça sera la même contribution sur la branche master. Même qu'on peut effacer le repos dans la branche master sur les fichiers en contributions dans le PR et ça passera.

2019-02-06 04:08 UTC, mikefaille commented
Je crois que c'est plus pratique le faire soit même le rebase / squash puisque ça nous positionne à revoir le résultat final.

2019-02-06 04:14 UTC, AXDOOMER commented
> Je crois que c'est plus pratique le faire soit même le rebase / squash puisque ça nous positionne à revoir le résultat final.

Non, car ça brise le workflow du peer review sur GitHub. C'est un étape de plus que le user faisant une soumission doit faire et ça complique les reviews, car le reviewer doit travailler en double.

2019-02-06 04:20 UTC, mikefaille commented
Ce qui rend inutile le workflow de Github, c'est ce que tu testes et revois n'a jamais été testé/revue au final.

2019-02-06 04:35 UTC, mikefaille commented
Pour détailler ma pensée, je propose de lire ça : https://gist.github.com/mbbx6spp/70fd2d6bf113b87c2719

2019-02-06 17:59 UTC, merged